language: ruby
script:
  - bundle exec jekyll build
  - bundle exec htmlproof _site/ --check-html --href-ignore https://untappd.com/user/pezholio
cache: bundler
sudo: false
branches:
  only:
    - gh-pages
