# Site settings
title: Train Beers
header-img: img/home-header.jpg
email: pezholio@gmail.com
description: "Mobile refreshment for the craft beer generation"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: pezholio
github_username:  pezholio/train-beers
facebook_username:  pezholio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
