# Site settings
title: Train Beers
header-img: img/header.jpg
email: pezholio@gmail.com
description: "Craft beer at 125mph"
baseurl: ""
url: "http://train-beers.pezhol.io/"
twitter_username: pezholio
github_username:  pezholio/train-beers
facebook_username:  pezholio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
